#!/bin/bash

# Make backups of all configs and dotfiles:
# my_configs.vim, dwm/dmenu config.h, .inputrc, .Xresources,
# .xinitrc, scripts/*, colors/updateColors

[[ $(whoami) != "root" ]] && { echo "Please run as root."; exit 1; }

root_home=/root
user_home=/home/chris
backups_dir=$user_home/backups

# Files in home dir
cat $user_home/.Xresources > $backups_dir/.Xresources
cat $user_home/.bashrc > $backups_dir/.bashrc
cat $user_home/.inputrc > $backups_dir/.inputrc
cat $user_home/.xinitrc > $backups_dir/.xinitrc

# Extra Vim configs
cat $user_home/.vim_runtime/my_configs.vim > $backups_dir/my_configs.vim

# .config dir configs
cat $user_home/.config/nvim/init.vim > $backups_dir/nvim/init.vim
cat $user_home/.config/ranger/rc.conf > $backups_dir/ranger/rc.conf

# Suckless utils configs
cat $root_home/dwm/config.h > $backups_dir/dwm/config.h 
cat $root_home/dmenu/config.h > $backups_dir/dmenu/config.h 

# Scripts
for file in $user_home/scripts/*; do
    cat "$file" > $backups_dir/scripts/${file##*/}
done
