#!/bin/bash

# Use default search engine of web browser to search for query

dmenuFirefoxSearch() {
  do_nothing() { return; }
  local query=$(do_nothing | dmenu -p "Search:")
  [[ $query =~ ^[[:space:]]*$ ]] && return
  firefox --search "$query" &
}

dmenuFirefoxSearch
