#!/bin/bash

# Scrapes Yahoo Finance's stock page for
# a ticker symbol and grabs the price.
# Called in update_status_bar
 
grab_nyse_price_webscrape() {

    [[ -z $1 ]] && { echo "missing option"; return; }

    symb=$1

    reactid="49" # could be 50 sometimes

    price=$(curl -s https://finance.yahoo.com/quote/${symb} \
      | grep "data-reactid=\"${reactid}\"" \
      | sed "s/.*data-reactid=\"${reactid}\">\([0-9]*\.[0-9][0-9]\)<.*/\1/g" \
    )

    echo $price
}
